org: adyptation
app: devops
service: webhooker

package:
  patterns:
    - "!venv/**"
    - "!tests/**"

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  stages:
    - dev
    - prod
  customDomain:
    domainName: webhooker.adypta.com
    stage: ${self:provider.stackTags.STAGE}
    basePath: ""
    certificateName: ${self:custom.certificateName.${self:provider.stackTags.STAGE}}
    createRoute53Record: true
    endpointType: "regional"
  certificateName:
    dev: "api.adypta.com"
    prod: "api.adypta.com"
  region:
    dev: ${ssm:/devops/region}
    prod: ${ssm:/devops/region}

provider:
  name: aws
  runtime: python3.9
  region: ${ssm:/devops/region}
  stackTags:
    PUBLIC: "True"
    PRODUCT: "Devops"
    TRIGGER: "HTTP"
    STAGE: ${opt:stage,"dev"}
    SERVICE: "webhooker"
  environment:
    SLACK_CHANNEL_SECURITY: ${ssm:/devops/slack/channel/security}
    SLACK_CHANNEL_DEVOPS: ${ssm:/devops/slack/channel/devops}
  ecr:
    images:
      webhooker-prod-app:
        path: ./
      webhooker-dev-app:
        path: ./

functions:
  app:
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"
    timeout: 30
    image:
      name: webhooker-${self:provider.stackTags.STAGE}-app
