org: adyptation
app: devops
service: webhooker
configValidationMode: error

package:
  patterns:
    - "!venv/**"
    - "!tests/**"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stackTags:
    PUBLIC: "True"
    PRODUCT: "devops"
    TRIGGER: "HTTP"
    STAGE: ${opt:stage,"dev"}
    SERVICE: "webhooker"
  environment:
    SLACK_CHANNEL_SECURITY: ${ssm:/devops/slack/channel/security}
    SLACK_CHANNEL_DEVOPS: ${ssm:/devops/slack/channel/devops}
  ecr:
    scanOnPush: true
    images:
      baseimage:
        path: ./
        file: Dockerfile

functions:
  app:
    image:
      name: baseimage
      command:
        - app.lambda_handler
    # logs:
    #   httpApi: true
  other:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"
